services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: process-dashboard-api
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./app:/app/app
    networks:
      edge:
        aliases:
          - process-dashboard-api

networks:
  edge:
    external: true