services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: process-dashboard-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./app:/app/app
      - ./.env:/app/.env:ro
    networks:
      - process-network

networks:
  process-network:
    driver: bridge