services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: process-visualization-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./app:/app/app

networks:
  process-network:
    driver: bridge